ProxyPreserveHost On

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule ^/socket.io/(.*) ws://uhub-api:4001/socket.io/$1 [P,L]

ProxyPass /socket.io/ http://uhub-api:4001/socket.io/
ProxyPassReverse /socket.io/ http://uhub-api:4001/socket.io/

ProxyPass /api/ http://uhub-api:4001/api/
ProxyPassReverse /api/ http://uhub-api:4001/api/

ProxyPass /data/ http://uhub-api:4001/data/
ProxyPassReverse /data/ http://uhub-api:4001/data/
