
export const countries: Record<string, string[]> = {
    "Afghanistan": [],
    "Albania": [],
    "Algeria": [],
    "Andorra": [],
    "Angola": [],
    "Antigua and Barbuda": [],
    "Argentina": [],
    "Armenia": [],
    "Australia": ["Australian Capital Territory", "New South Wales", "Northern Territory", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia"],
    "Austria": [],
    "Azerbaijan": [],
    "Bahamas": [],
    "Bahrain": [],
    "Bangladesh": [],
    "Barbados": [],
    "Belarus": [],
    "Belgium": [],
    "Belize": [],
    "Benin": [],
    "Bhutan": [],
    "Bolivia": [],
    "Bosnia and Herzegovina": [],
    "Botswana": [],
    "Brazil": [],
    "Brunei": [],
    "Bulgaria": [],
    "Burkina Faso": [],
    "Burundi": [],
    "Cabo Verde": [],
    "Cambodia": [],
    "Cameroon": [],
    "Canada": ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"],
    "Central African Republic": [],
    "Chad": [],
    "Chile": [],
    "China": [],
    "Colombia": [],
    "Comoros": [],
    "Congo, Democratic Republic of the": [],
    "Congo, Republic of the": [],
    "Costa Rica": [],
    "Cote d'Ivoire": [],
    "Croatia": [],
    "Cuba": [],
    "Cyprus": [],
    "Czech Republic": [],
    "Denmark": [],
    "Djibouti": [],
    "Dominica": [],
    "Dominican Republic": [],
    "Ecuador": [],
    "Egypt": [],
    "El Salvador": [],
    "Equatorial Guinea": [],
    "Eritrea": [],
    "Estonia": [],
    "Eswatini": [],
    "Ethiopia": [],
    "Fiji": [],
    "Finland": [],
    "France": [],
    "Gabon": [],
    "Gambia": [],
    "Georgia": [],
    "Germany": [],
    "Ghana": [],
    "Greece": [],
    "Grenada": [],
    "Guatemala": [],
    "Guinea": [],
    "Guinea-Bissau": [],
    "Guyana": [],
    "Haiti": [],
    "Honduras": [],
    "Hungary": [],
    "Iceland": [],
    "India": [],
    "Indonesia": [],
    "Iran": [],
    "Iraq": [],
    "Ireland": [],
    "Israel": [],
    "Italy": [],
    "Jamaica": [],
    "Japan": [],
    "Jordan": [],
    "Kazakhstan": [],
    "Kenya": [],
    "Kiribati": [],
    "Kosovo": [],
    "Kuwait": [],
    "Kyrgyzstan": [],
    "Laos": [],
    "Latvia": [],
    "Lebanon": [],
    "Lesotho": [],
    "Liberia": [],
    "Libya": [],
    "Liechtenstein": [],
    "Lithuania": [],
    "Luxembourg": [],
    "Madagascar": [],
    "Malawi": [],
    "Malaysia": [],
    "Maldives": [],
    "Mali": [],
    "Malta": [],
    "Marshall Islands": [],
    "Mauritania": [],
    "Mauritius": [],
    "Mexico": ["Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Mexico City", "Mexico State", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"],
    "Micronesia": [],
    "Moldova": [],
    "Monaco": [],
    "Mongolia": [],
    "Montenegro": [],
    "Morocco": [],
    "Mozambique": [],
    "Myanmar": [],
    "Namibia": [],
    "Nauru": [],
    "Nepal": [],
    "Netherlands": [],
    "New Zealand": [],
    "Nicaragua": [],
    "Niger": [],
    "Nigeria": [],
    "North Korea": [],
    "North Macedonia": [],
    "Norway": [],
    "Oman": [],
    "Pakistan": [],
    "Palau": [],
    "Palestine": [],
    "Panama": [],
    "Papua New Guinea": [],
    "Paraguay": [],
    "Peru": [],
    "Philippines": [],
    "Poland": [],
    "Portugal": [],
    "Qatar": [],
    "Romania": [],
    "Russia": [],
    "Rwanda": [],
    "Saint Kitts and Nevis": [],
    "Saint Lucia": [],
    "Saint Vincent and the Grenadines": [],
    "Samoa": [],
    "San Marino": [],
    "Sao Tome and Principe": [],
    "Saudi Arabia": [],
    "Senegal": [],
    "Serbia": [],
    "Seychelles": [],
    "Sierra Leone": [],
    "Singapore": [],
    "Slovakia": [],
    "Slovenia": [],
    "Solomon Islands": [],
    "Somalia": [],
    "South Africa": [],
    "South Korea": [],
    "South Sudan": [],
    "Spain": [],
    "Sri Lanka": [],
    "Sudan": [],
    "Suriname": [],
    "Sweden": [],
    "Switzerland": [],
    "Syria": [],
    "Taiwan": [],
    "Tajikistan": [],
    "Tanzania": [],
    "Thailand": [],
    "Timor-Leste": [],
    "Togo": [],
    "Tonga": [],
    "Trinidad and Tobago": [],
    "Tunisia": [],
    "Turkey": [],
    "Turkmenistan": [],
    "Tuvalu": [],
    "Uganda": [],
    "Ukraine": ["Cherkasy Oblast", "Chernihiv Oblast", "Chernivtsi Oblast", "Crimea", "Dnipropetrovsk Oblast", "Donetsk Oblast", "Ivano-Frankivsk Oblast", "Kharkiv Oblast", "Kherson Oblast", "Khmelnytskyi Oblast", "Kyiv Oblast", "Kirovohrad Oblast", "Luhansk Oblast", "Lviv Oblast", "Mykolaiv Oblast", "Odessa Oblast", "Poltava Oblast", "Rivne Oblast", "Sumy Oblast", "Ternopil Oblast", "Vinnytsia Oblast", "Volyn Oblast", "Zakarpattia Oblast", "Zaporizhzhia Oblast", "Zhytomyr Oblast"],
    "United Arab Emirates": [],
    "United Kingdom": [],
    "USA": ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"],
    "Uruguay": [],
    "Uzbekistan": [],
    "Vanuatu": [],
    "Vatican City": [],
    "Venezuela": [],
    "Vietnam": [],
    "Yemen": [],
    "Zambia": [],
    "Zimbabwe": []
};
